Connection + Refactoring
ToxicButterfly/DriverService pull request #4
Opened 2024-01-30 10:33 UTC by ToxicButterfly

2024-01-31 06:25 UTC, AbandonedScope requested changes

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/controller/DriverController.java
>  @RequestMapping("api/v1/driver")
Принято писать в множественном числе при названии эндпоинтов - не driver, а drivers

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/controller/DriverController.java
> +    public ResponseEntity<DriverDto> getDriver(@RequestBody @Valid LoginDto loginDTO) throws InvalidLoginException {
В Java при именовании переменных, классов, интерфейсов и тд используется camelcase, то есть:  loginDTO -> loginDto

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/controller/DriverController.java
Почему у тебя в методах контроллера пробрасываются какие-то исключения?
Убери это

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/controller/DriverController.java
>      }
Если этот эндпоинт не перезаписывает рэйтинг, а добавляет новую оценку, то поменяй метод на Post, иначе - оставляй как есть

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/dto/LoginDto.java
>      @Email(message = "Email should be valid")
Сообщения об ошибках читай из файла конфигураций(для обеспечения локализации) ИЛИ можешь возвращать не сами сообщения, а к ключ (что-то вроде message.validation.email) а фронт сам разберётся, что вместо этого писать

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/dto/RatingResponse.java
> +
Тут пустую строку убери и добавь в конец файла

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/kafka/DriverProducer.java
> +public class DriverProducer {
Можешь как-нибудь более говоряще назвать

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/kafka/RidesConsumer.java
> +public class RidesConsumer {
Смени название на более подробное

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/controller/DriverController.java
> +    final DriverServiceImpl driverService;
Во первых - private, во вторых - инжэкть DriverService, a не DriverServiceImpl

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +        return drivers;
```suggestion
        return new DriversDto(driverRepo.findAll().stream()
                .map(driverDtoConverter::convertDriverToDriverDto)
                .toList());
```

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +    public DriverDto register(Driver driver) throws InvalidLoginException {
А пароль не хэшируется?
В базе данных нельзя хранить незахэшированный пароль, иначе любой человек сможет войти в аккаунт пользователя

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +                .orElseThrow(() -> new InvalidLoginException("Invalid email or password"));
Вытягивать нужно по логину, и потом проверять пароль, т.к. в бд он должен храниться в захэшированном состоянии

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +                .orElseThrow(() -> new UserNotFoundException("There's no such driver"));
У тебя связка findById(id).orElseThrow.... несколько раз повторяется, ты можешь вынести это в отдельный метод и назвать как-нибудь вроде getOrThrow...

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +    }
Для чего это?

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +        Driver driver = driverRepo.findById(id).get();
А если такого водителя нет?

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +    }
Для чего это?

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/resources/db/changelog/v-1.0/01-changeset-driver-table.xml
> +    <changeSet id="2" author="Toxic Bfly">
Почему id - 2?

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/resources/db/changelog/db.changelog-master.xml
> +    <changeSet id="4" author="Toxic Bfly">
Почему id - 4?

2024-01-31 06:25 UTC, AbandonedScope commented on src/main/resources/db/changelog/v-1.0/01-create-driver-table.sql
> +VALUES ('Иван Иванов', 'Vanyuha', 'Vano228@tut.by', 'Vanya228', '12-12-2015', true, '3.0');
Вот это лучше отдельным changeSet-ом

2024-02-01 18:04 UTC, ToxicButterfly commented on src/main/java/com/example/driverservice/controller/DriverController.java
>      }
У водителя хранится только его средняя оценка, она и обновляется

2024-02-01 18:41 UTC, ToxicButterfly commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +    public DriverDto register(Driver driver) throws InvalidLoginException {
Разумеется, пароли хранить в не зашифрованном виде нельзя, но пока что эта версия регистрации и авторизации примитивная, добавлю шифрование вместе с Security позже.

2024-02-01 18:42 UTC, ToxicButterfly commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +                .orElseThrow(() -> new InvalidLoginException("Invalid email or password"));
Учту на будущее

2024-02-01 18:46 UTC, ToxicButterfly commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +    }
Сервис Payment запрашивает у водителя и пассажира данные их банковских карт и проводит "транзакцию".

2024-02-01 18:47 UTC, ToxicButterfly commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +    }
Пассажир и водитель после поездки выставляют оценку водителю и пассажиру соответственно. Сервис Rating занимается в том числе и опросом.

2024-02-01 18:49 UTC, ToxicButterfly commented on src/main/java/com/example/driverservice/service/impl/DriverServiceImpl.java
> +        Driver driver = driverRepo.findById(id).get();
Это водитель, которого мы уже отыскали и который участвовал в поездке. Он должен быть

2024-02-05 08:55 UTC, AbandonedScope approved these changes

2024-02-05 13:17 UTC, merged